port = 8080
# port = 8443
https = false
cache_busting = false

[redirect_server]
port = 8081
enabled = false

[watch]
frontend = [
    "public",
    "frontend/Cargo.toml",
    "frontend/src",
]
backend = [
    "backend/Cargo.toml",
    "backend/src",
]
